services:
  - type: web
    name: birthday-likitha-2026
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn run:app
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_RECEIVER
        sync: false
